### ISSUE TITLE
events.js:160 ->throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by ChrisRichner** [sgbj/generator-aspnetcore-angular2#19]
I've just installed the generator on my Machine (Windows 10 x64  14393.187, npm 3.3.12, node v6.4.0) 

After asking _What's the project name (this will also be your namespace name)?_ it fails immediately with the following error.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (C:\Users\Christoph\AppData\Roaming\npm\node_modules\generator-aspnetcore-angular2\node_modules\yeoman-generator\lib\base.js:232:45)
    at module.exports.yeoman.Base.extend.prompting (C:\Users\Christoph\AppData\Roaming\npm\node_modules\generator-aspnetcore-angular2\generators\app\index.js:36:17)
    at Object.<anonymous> (C:\Users\Christoph\AppData\Roaming\npm\node_modules\generator-aspnetcore-angular2\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\Christoph\AppData\Roaming\npm\node_modules\generator-aspnetcore-angular2\node_modules\run-async\index.js:26:25
    at C:\Users\Christoph\AppData\Roaming\npm\node_modules\generator-aspnetcore-angular2\node_modules\run-async\index.js:25:19
    at C:\Users\Christoph\AppData\Roaming\npm\node_modules\generator-aspnetcore-angular2\node_modules\yeoman-generator\lib\base.js:432:9
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by sgbj** [comment]
What `yo --version` are you running? I'm using the latest (1.8.5) and it's working for me. Updating yo seems to be the [suggested answer](http://stackoverflow.com/questions/37193740/error-unhandled-error-event-after-running-yo-generator) for this error message.

**Comment by ChrisRichner** [comment]
My Bad! After I've updated npm and yo it worked flawlessly!

Thanks
