### ISSUE TITLE
Cannot find module 'aspnet-webpack'

### ISSUE THREAD

**Issue by stmart76** [sgbj/generator-aspnetcore-angular2#23]
Running on Windows Server 2008 with IIS.

I cannot get past this error.

Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
 at Function.Module._resolveFilename (module.js:469:15)
 at Function.Module._load (module.js:417:25)
 at Module.require (module.js:497:17)
 at require (internal/module.js:20:19)
 at module.exports.createWebpackDevServer (C:\Windows\TEMP\tmp193B.tmp:5:25)
 at C:\Windows\TEMP\tmp1A54.tmp:113:19
 at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp1A54.tmp:132:38)
 at emitNone (events.js:86:13)
 at IncomingMessage.emit (events.js:185:7)
 at endReadableNT (_stream_readable.js:974:12)

**Comment by sgbj** [comment]
This is probably an oversight on my part. You may need to add the node_modules folder to the include section of your project.json:

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config",
      "node_modules"      <------
    ],
    "exclude": [
      "wwwroot/src",
      "wwwroot/e2e"
    ]
  },
```

Of course, that's a lot to have to pull over. I'll look into finding a better way to package that dependency for deployments. It's required for the aspnet prerendering.

**Comment by stmart76** [comment]
I will need to revisit as I went back to my old project setup but I did think this solution so i put up the package.json and did an npm install on the server.  Still the same.

Thanks for your reply.

**Comment by DaveConsulting** [comment]
I have the same issue and get the exact error:
Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

The "node_modules" is already in the project.json. So I guess that's not the solution. Any other suggestion?

**Comment by DaveConsulting** [comment]
After installing a couple of packages manually, I saw different error telling me about not finding other packages. So I guess the problem was that I didn't gave enough time to Visual Studio to restore and install all the packages. When all the packages were installed, it worked and I see the first page :-)

**Comment by 408796571** [comment]
@DaveConsulting Thanks for sharing, I'm running into exactly same issue. Could you be more specific on what packages did you install manually? It seems that I always have some packages not installed in visual studio.

**Comment by diegomesata** [comment]
@Mark-Brightcloud My npm_modules folder was empty, that means that the npm dependencies specified in package.json were not installed. 

Option 1) In VS, Solution Explorer, Right click on Dependencies->npm, Restore Packages. In Output Window you could get an error, and nothing is installed. That not worked for me, because my VS is using node v0.10.26, you could check your version in Package Manager Console, write the command 
node -v
v0.10.26

Option 2) Check that you have installed Node.js https://nodejs.org/en/download/ . Open "Node.js command promp" from the Node.js folder on Windows Button. My version is v4.4.5.

Go to the project directory cd c:\...\Angular2AspCoreXXX and exec the command "npm install".

Option 3) In VS, Tools, Options, External Web Tools, fix or add the path to nodejs, restart VS and try option 1.

The projects runs now!

Bye, hope this helps.

**Comment by asp-entwickler** [comment]
In my case, the following solution works
npm install aspnet-webpack -D
and in 
webpack.config.json

	output: {
		....
		publicPath: '/dist/'      //  <--  Important
	},
