### ISSUE TITLE
Cannot find module './0.webpack-output.js'

### ISSUE THREAD

**Issue by kjartanvalur** [sgbj/generator-aspnetcore-angular2#24]
Lazy loading is not working properly.

If you create a new project (advanced) and navigate to about and try to refresh. Then I get the following error.

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Uncaught (in promise): **Error: Cannot find module './0.webpack-output.js'**
Error: Cannot find module './0.webpack-output.js'
at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at Function.requireEnsure [as e](C:DataPROGRAMSgenerator-aspnetcore-angular2srcTestProjwwwrootsrcserver.js:40:25)
at C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\wwwroot\src\server.js:258:110
at new ZoneAwarePromise (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:518:29)
at loadChildren (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\wwwroot\src\server.js:258:57)
at RouterConfigLoader.loadModuleFactory (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\@angular\router\bundles\router.umd.js:172:80)
at RouterConfigLoader.load (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\@angular\router\bundles\router.umd.js:160:52)
at resolvePromise (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:468:31)
at C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:445:13
at ZoneDelegate.invoke (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:232:26)
at Object.onInvoke (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\@angular\core\bundles\core.umd.js:6229:41)
at ZoneDelegate.invoke (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:231:32)
at Zone.run (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:114:43)
at C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:502:57
at ZoneDelegate.invokeTask (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:265:35)
at Object.onInvokeTask (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\@angular\core\bundles\core.umd.js:6220:41)
at ZoneDelegate.invokeTask (C:\Data\PROGRAMS\generator-aspnetcore-angular2\src\TestProj\node_modules\zone.js\dist\zone-node.js:264:40)

**Comment by sgbj** [comment]
This is happening with the aspnet prerendering turned on. The workaround for now is to comment out the asp-prerender-module attribute in Index.cshtml, then it should work. I'll look into getting this working with prerendering turned on.

```
<app-root @*asp-prerender-module="wwwroot/src/server"*@ asp-prerender-webpack-config="webpack.config.js">
    Loading...
</app-root>
```

**Comment by kjartanvalur** [comment]
Thanks for quick response. This means no Universal support with lazy loading in the moment?

**Comment by sgbj** [comment]
That's correct, you can either remove the lazy loading or remove the universal for now. I'll look into getting them both working together.

**Comment by kjartanvalur** [comment]
@sgbj  any progress?

**Comment by sgbj** [comment]
I haven't found a way to resolve this issue.

I changed the output section in the `webpack.dev.js` to specify the `chunkFilename`:

``` js
    output: {
        path: path.resolve(__dirname, '../wwwroot/dist'),
        filename: '[name].bundle.js',
        sourceMapFilename: '[name].map',
        publicPath: '/dist/',
        chunkFilename: "../dist/[id].bundle.js"
    },
```

And it is able to find the module at that point. However, a different error occurs:

```
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Uncaught (in promise): ReferenceError: webpackJsonp is not defined
ReferenceError: webpackJsonp is not defined
at Object.<anonymous> (C:\Users\...\WebApp\src\WebApp\wwwroot\dist\0.bundle.js:1:1)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
```

I'm having a difficult time finding an example of an Angular Universal application that has lazy routes. If I could find a working implementation I might get a better idea of what's going wrong.
